### ISSUE TITLE
Champs "Dimensions"

### ISSUE THREAD

**Issue by Pepite-World** [Pepite-World/slideur-pepite#1]
Les champs qui se trouvent dans “dimensions” de chaque slide influent sur la taille entière de la slide et non juste l’image ou la video.

![Capture d’écran 2024-09-04 à 16 24 25](https://github.com/user-attachments/assets/513b8b74-eea3-4258-9b6b-dbd096c78b4c)
![Capture d’écran 2024-09-04 à 16 25 23](https://github.com/user-attachments/assets/7d0f8f6d-b9fd-4067-a780-3358fd4b8cc9)
![Capture d’écran 2024-09-04 à 16 25 30](https://github.com/user-attachments/assets/5b42344f-cfe4-48d1-b06d-89c760a1f4bf)

**Comment by 5AMsan** [comment]
Hum... Que me dis-tu là ? 
![image](https://github.com/user-attachments/assets/29d8c9f6-b20e-4350-8188-c99a9c2a1e2b)

**Comment by 5AMsan** [comment]
Je note que d'une façon générale, il faut choisir si on privilégie hauteur ou largeur pour les calculs en fallback et par défaut.
On en reparle après la prochaine MAJ.

**Comment by Pepite-World** [comment]
J'ai fait plusieurs tests sur les hauteur à 100% mais les tailles en hauteur/largeur ne changent pas. 

![Capture d’écran 2024-09-10 à 11 00 54](https://github.com/user-attachments/assets/0b667bb1-689a-422a-89f6-0cec18d5b931)

Le comportement des images et des videos me gênent. Il faudrait que les images et vidéos prennent par défaut 100% de la hauteur, et que lorsque la fenêtre est plus petite le visuel est croppé en largeur.  

![Capture d’écran 2024-09-10 à 11 15 42](https://github.com/user-attachments/assets/8f94248b-0c60-4013-b11b-2b4f58c7f6e6)

Comme sur https://www.republique.studio/ aussi. 

Exemple de ce qu'il y a actuellement ![Capture d’écran 2024-09-10 à 11 21 04](https://github.com/user-attachments/assets/834ff43a-5dd0-4461-8081-bf8543b53d18)


Par contre, l'idée est qu'on puisse jouer sur la hauteur pour que l'image ou la video ne prenne pas toute la hauteur. 
Si ce n'est pas clair on peut s'appeler

**Comment by 5AMsan** [comment]
Tu peux test pour la vidéo comment ça se comporte chez toi plz

**Comment by Pepite-World** [comment]
J'ai voulu tester le comportement des vidéos comme tu me l'as demandé hier matin mais tu as dû changer le plugin entre temps non ? Ce n'est plus le même entre hier matin et hier soir. Le zoom de la premiere slide ne se fait plus. 

Hier matin, j'ai eu juste le temps de voir que la première slide avec l'image des deux posters du faire se comportait bien
avec le zoom quand on resize l'image. Pour la slide 2 avec la tasse, vu que par défaut la largeur est à 100% l'image est croppée quand on met la hauteur à 40%. Pour remédier à ça, j'ai dû ajouter dans le champ css de l'image de la slide "width:auto!important" pour que l'image garde son ratio. Est-ce que c'est possible d'ajouter dans le plugin un truc dans le style : Si la hauteur de l'image fait moins de 100% alors sa largeur passe en auto ?

Je suis en formation ce matin mais on peut s'appeler à partir du début d'aprem si tu veux.

**Comment by 5AMsan** [comment]
> J'ai voulu tester le comportement des vidéos comme tu me l'as demandé hier matin mais tu as dû changer le plugin entre temps non ? Ce n'est plus le même entre hier matin et hier soir. Le zoom de la premiere slide ne se fait plus. Hier matin, j'ai eu juste le temps de voir que la première slide avec l'image des deux posters du faire se comportait bien avec le zoom quand on resize l'image. 

Pou moi ça semble toujours ok :/ 
![image](https://github.com/user-attachments/assets/e7934ac0-b368-4862-a864-545eb4ae86f2)

**Comment by 5AMsan** [comment]
T'aurais pas mis une vieille version du plugin par hasard...

**Comment by 5AMsan** [comment]
Han non, c'est moi p'tet...

**Comment by Pepite-World** [comment]
Ouais j'ai rien touché ^^ tu me dis quand tu as pu mettre la derniére version du plugin. Et pour ma demande pour la slide 2 ? 

"Pour la slide 2 avec la tasse, vu que par défaut la largeur est à 100% l'image est croppée quand on met la hauteur à 40%. Pour remédier à ça, j'ai dû ajouter dans le champ css de l'image de la slide "width:auto!important" pour que l'image garde son ratio. Est-ce que c'est possible d'ajouter dans le plugin un truc dans le style : Si la hauteur de l'image fait moins de 100% alors sa largeur passe en auto ?"

**Comment by 5AMsan** [comment]
J'ai mis à jour. Mais je galère sur les flèches qui veulent pas partir sur ton site, sur le mien j'ai pas de souci portant, j'ai même les curseur

**Comment by Pepite-World** [comment]
Ah yes c'est bon pour le zoom de l'image, effectivement y'a encore les fléches... mais dans le dernier plugin que tu avais mis hier matin c'était bon. C'est bizarre.  Question con hein, mais ce n'est pas une question que "afficher les fleches" soit sur on peut-être ? Et il faut mettre deux images pour que le curseur s'affiche. 

Et pour ma demande pour la slide 2 ? 

"Pour la slide 2 avec la tasse, vu que par défaut la largeur est à 100% l'image est croppée quand on met la hauteur à 40%. Pour remédier à ça, j'ai dû ajouter dans le champ css de l'image de la slide "width:auto!important" pour que l'image garde son ratio. Est-ce que c'est possible d'ajouter dans le plugin un truc dans le style : Si la hauteur de l'image fait moins de 100% alors sa largeur passe en auto ?"

**Comment by 5AMsan** [comment]
> Et pour ma demande pour la slide 2 ?

Pour moi c'est OK
![image](https://github.com/user-attachments/assets/592dbf7e-326c-46da-95bc-eb69f4655743)

**Comment by Pepite-World** [comment]
Ca fonctionne car j'ai ajouté dans le champ css de l'image de la slide "width:auto!important" pour que l'image garde son ratio. Est-ce que c'est possible d'ajouter dans le plugin un truc dans le style : Si la hauteur de l'image fait moins de 100% alors sa largeur passe en auto automatiquement ?

![Capture d’écran 2024-09-12 à 16 12 47](https://github.com/user-attachments/assets/4780cedd-dd4d-435e-8903-604a570efa7a)

**Comment by 5AMsan** [comment]
bah vire le que je puisse debug

**Comment by Pepite-World** [comment]
C'est enlevé :)

**Comment by 5AMsan** [comment]
J'ai fixé

**Comment by Pepite-World** [comment]
Nickel pour la seconde slide, par contre sur la premiere avec l'image à hauteur 100% on voit le fond quand on est sur un grand écran. Quand j'enlève le width:100% de la classe .et_pb_module.pesl_pepite_slider .et_pb_slide_image>img l'image va au bord de l'écran mais ca pète le ratio de la slide 2 ... 

![Capture d’écran 2024-09-12 à 17 43 19](https://github.com/user-attachments/assets/d62fac41-5761-4816-be8e-95a72ace408e)

**Comment by 5AMsan** [comment]
Bah oui, ton image n'a pas un ratio suffisant pour remplir, sauf si tu la mets à plus de 100% j'imagine...

**Comment by Pepite-World** [comment]
Même si je mets sa valeur width à plus de 100%, elle ne va pas jusqu'au bout de l'écran vu que la hauteur est toujours à 100%.  Il faudrait que de base, quelque soit le ratio de l'image, elle aille jusqu'au bout de l'écran avec une hauteur de 100% (comme on avait vu ensemble, elle zoome) et si la hauteur indiquée est moins de 100% alors width passe en auto pour que le ratio de l'image soit conservée et qu'on voit pas une image en bande avec une hauteur à 40% et un width à 100%. 

Si ce n'est pas possible, au pire des cas je pourrai indiquer à la mano  dans le champ css de l'image de la slide "width:auto!important" quand j'ai une hauteur inférieure à 100% comme il y avait avant.

**Comment by 5AMsan** [comment]
Ils ont tous l'air OK
