### ISSUE TITLE
Pointer Events video en iframe

### ISSUE THREAD

**Issue by 5AMsan** [Pepite-World/slideur-pepite#10]
la vidéo prend le dessus pour les écouteurs d'évènements,  on ne peut pas changer de slide si la vidéo prend toute la zone affichable.
Devrait être fixé avec :
```
.et_pb_slide_video .fluid-width-video-wrapper iframe, 
.et_pb_slide_video .fluid-width-video-wrapper object,
.et_pb_slide_video  .fluid-width-video-wrapper embed {
  pointer-events: none;
}
```

**Comment by Pepite-World** [comment]
C'est good j'ai ajouté ça aussi : 

.fluid-width-video-wrapper {
    pointer-events: none;
}

**Comment by 5AMsan** [comment]
Je le passerai dans la soirée

Le ven. 13 sept. 2024, 14:27, Pepite-World ***@***.***> a
écrit :
