### ISSUE TITLE
Changement de slide au click du lien titre

### ISSUE THREAD

**Issue by Pepite-World** [Pepite-World/slideur-pepite#11]
Lorsque je change clique sur le titre de la slide, le slider change de slide avant d'ouvrir l'url du titre (video dans le message suivant). 
Ca devient un plus gros soucis sur le tel, quand je clique sur le nom la slide change et ne va pas sur l'url.

**Comment by Pepite-World** [comment]
https://github.com/user-attachments/assets/48d30d15-e9bf-45c9-bc98-b64e83e1a90e

**Comment by 5AMsan** [comment]
J'essaie de fixer, mais j'arrive pas à avoir le même bug que sur ta mise en page... Je te tiens au courant
