### ISSUE TITLE
Chargement des vidéos

### ISSUE THREAD

**Issue by Pepite-World** [Pepite-World/slideur-pepite#13]
Est-il possible de charger l'iframe de la vidéo sur la slide précédente pour éviter qu'elle "pop" après que l'on soit sur la slide ? 

https://github.com/user-attachments/assets/1717d8fb-5845-40a8-9ac8-ec362e891607

**Comment by 5AMsan** [comment]
Je l'ai dit plus tôt, c'est la lecture en boucle qui fait que les objets se déchargent. Je suis pas certain que ce soit fixable sauf à virer la boucle.

**Comment by Pepite-World** [comment]
D'acc, si on ne peut pas faire autrement c'est pas bien grave

**Comment by Pepite-World** [comment]
Est-ce que c'est possible d'avoir la miniature de la video pendant son chargement ?

**Comment by Pepite-World** [comment]
C'est bon ca marche si je mets en background une image ! Idée de génie merci :) !
