### ISSUE TITLE
Safari et Firefox

### ISSUE THREAD

**Issue by Pepite-World** [Pepite-World/slideur-pepite#14]
J'ai demandé aux autres de tester le slider sur safari et ils me disent qu'ils ne peuvent pas cliquer sur le carrousel ni sur le menu du haut. Ils ont la derniere version la 17. 

De mon coté, j'ai la version 14 et je peux cliquer mais les vidéos ne s'affichent pas. Tu pourrais regarder de ton coté ? 
Je n'ai pas tester sur firefox, je regarderai dés que possible.

**Comment by 5AMsan** [comment]
TU me dis que tu n'as pas de video visible, c'est ça ?

**Comment by Pepite-World** [comment]
Sur ma version de safari (la 14) la video n'est pas visible et sur celle des autres, la 17 la plus récente donc, le carrousel et le header ne sont pas cliquables. Tu peux tester safari sur ta machine ?

**Comment by 5AMsan** [comment]
![image](https://github.com/user-attachments/assets/4e4f4f09-dedf-4831-a9fc-6f5fc9d51191)
Cette boite bloque les interaction sur FF mais ni sur Chrome, ni sur Edge, tu sais quel module la génère ?

**Comment by Pepite-World** [comment]
Oui c'est mon preloader que j'ai mis dans le header, j'ai testé en le supprimant et ca fonctionne sur safari. Je vais le remettre, tu pourras regarder pourquoi ca bloque ?

**Comment by 5AMsan** [comment]
parce qu'il permet l'utilisation des événement de pointeur, met lui un
`pointer-events: none`, ça devrait régler le problème.

Le lun. 16 sept. 2024 à 12:01, Pepite-World ***@***.***> a
écrit :

**Comment by Pepite-World** [comment]
Nickel ca marche merci !
