### ISSUE TITLE
Vimeo > Youtube 

### ISSUE THREAD

**Issue by Pepite-World** [Pepite-World/slideur-pepite#15]
Désolé mais on a un gros soucis avec Vimeo puisque les vidéos ne se lancent pas en automatique sur Safari... j'ai testé avec un lien youtube et la video se lance sans soucis. Je te propose de changer le champs d'intégration des videos pour qu'il prenne les videos issues de youtube plutot que celles de vimeo.  J'ai vu qu'il était possible d'avoir le lecteur youtube sans rien : https://codepen.io/Terrafire123/pen/yLayQvM

Sais-tu si il est possible de s'assurer qu'on aura aucune pub ou une présentation des vidéos relatives ? J'ai regardé sur Youtube Pro mais je n'arrive pas à trouver.

**Comment by 5AMsan** [comment]
Non, la pub est contrôlée par l'utilisateur final, pas par le compte qui
publie.

Le lun. 16 sept. 2024 à 14:56, Pepite-World ***@***.***> a
écrit :

**Comment by Pepite-World** [comment]
Ah merde bon ben on laisse tomber alors si on est pas sur à 100% de pas avoir de pub...il va falloir qu'on passe par de la vidéo qu'on héberge direct sur wordpress. Tu pourrais ajouter un champ pour la video direct hébergée stp ?

**Comment by 5AMsan** [comment]
J'ai passé une maj pour la lecture Vimeo du 1er slide. Malheureusement, c'est le browser qui bloque..
player.js:2 
 Uncaught (in promise) NotAllowedError: play() failed because the user didn't interact with the document first.

**Comment by Pepite-World** [comment]
Damn bien relou ce vimeo... dans ce cas si il n'y aucune solution peux-tu passer par un champ où l'on upload de la video en direct ?

**Comment by 5AMsan** [comment]
C'est good elle se lit chez moi, tu teste plz

**Comment by Pepite-World** [comment]
Elles ne se lisent pas sur mon iphone que ca soit safari ou chrome, je demanderai aux autres si sur leur safari sur mac ca marche demain matin.

**Comment by 5AMsan** [comment]
T'es certain d'avoir un cache propre ?

**Comment by Pepite-World** [comment]
Oui j'ai supprimé toutes les données et images en cache

**Comment by Pepite-World** [comment]
Ah ! Attends, j'ai trouvé (peut-être) pourquoi ca ne marchait pas ! https://help.vimeo.com/hc/en-us/articles/12426486963857-Autoplay-and-loop-embedded-videos 

En batterie faible, la lecture en autoplay est désactivée. Sur mon Iphone ca marche ! Je demande aux autres demain matin si de leur coté c'est bon aussi

**Comment by Pepite-World** [comment]
C'est bon du coté de safari, les vidéos se lancent !
