### ISSUE TITLE
Autoplay 

### ISSUE THREAD

**Issue by Pepite-World** [Pepite-World/slideur-pepite#16]
Est-il possible d'ajouter une fonction autoplay au slider en on off ? C'est très pratique sur le téléphone par exemple quand on a pas les flèches.

**Comment by 5AMsan** [comment]
C'est en place, j'ai un bug avec mon Divi mais ça a l'air OK chez toi

**Comment by Pepite-World** [comment]
L'autoplay bug avec la transition "none", elle s'arrête à la slide 2. Tu pourrais regarder si c'est juste un ptit truc a modifier ou si tu penses que c'est plus relou ?

**Comment by 5AMsan** [comment]
C'est fixé.
