### ISSUE TITLE
Mobile Ipad Touch

### ISSUE THREAD

**Issue by Pepite-World** [Pepite-World/slideur-pepite#17]
Quand on est sur mobile ou tablette, le touch pour aller vers la slide d'aprés fonctionne (en touchant la slide sur la droite) par contre il faudrait qu'en touchant la slide sur la gauche on revienne sur la slide d'avant. C'est possible ? 

J'ai vu quand glissant le doigt ca fonctionne mais pas au touch. 

Uploading Enregistrement de l’écran 2024-09-20 à 14.36.51.mov…

**Comment by 5AMsan** [comment]
C'est pas lié au fait que tu n'ais pas de boucle ?

**Comment by Pepite-World** [comment]
J'ai une boucle pourtant : 
![Capture](https://github.com/user-attachments/assets/6f3bb881-351b-4662-9e12-37f7e466af87)
