### ISSUE TITLE
Ancre menu

### ISSUE THREAD

**Issue by Pepite-World** [Pepite-World/slideur-pepite#18]
J'ai une ancre sur le lien "A propos" qui doit scroller jusqu'à la section #a-propos
Ca fonctionne sur chrome mais pas sur safari ni firefox. Ca doit peut-être venir du changement de couleur/de classe car quand je désactive le plugin slider l'ancre fonctionne.

**Comment by 5AMsan** [comment]
t'utilises du code pour le scroll ?

**Comment by Pepite-World** [comment]
Non c'est une fonction qui est native à Divi. Ca marche sur chrome par contre hmmm

**Comment by 5AMsan** [comment]
Tu peux désactiver ta fonction voir si on peut avoir le scroll natif de FF qui fonctionne ?

**Comment by Pepite-World** [comment]
Je ne peux pas désactiver la fonction sur divi. Par contre j'utilise des ancres aussi sur https://www.edition4.figure-e.com/ et ca marche sur firefox et safari. J'ai l'impression que c'est un soucis avec Divi et non ton plugin. J'ai fait un ticket chez eux pour voir, j'te dis !

**Comment by 5AMsan** [comment]
Je te laisse tester, j'ai désactivé le smooth-scroll de Divi, ça scroll sous FF ici.
Tu peux le réactiver en  virant la classe que j'ai ajouté au menu concerné.

**Comment by Pepite-World** [comment]
Le support a fait un test sur une autre page : https://wip.pepite.world/anchor-test/ où les ancres fonctionnent et il me dit que ca vient surement d'un conflit avec le plugin du slider.

**Comment by 5AMsan** [comment]
oué mais ça on avait compris.
Ton header, qui sert au calcul du smoothscroll a une hauteur qui correspond à la hauteur de l'écran. Donc quand le smoothscroll (le script Divi) retranche la hauteur du header fix à la position de l'ancre, on a moins que 0, donc on scroll pas.
![image](https://github.com/user-attachments/assets/16772bff-d4d7-4199-8a36-df1fc548c8b5)

Je t'avais déjà fait la remarque que ton header était foiré

**Comment by 5AMsan** [comment]
![image](https://github.com/user-attachments/assets/e35d4dfa-afe2-4a88-be3a-b2daade1a205)

**Comment by 5AMsan** [comment]
Je vois pas trop comment debug le script Divi là... Tu peus tester avec un header à la bonne hauteur voir ?

**Comment by 5AMsan** [comment]
Le même calcul avec Edge et Chrome :
![image](https://github.com/user-attachments/assets/7b06a4e8-ac15-4e15-969f-7de34bf674e5)

**Comment by Pepite-World** [comment]
Je t'avoue que je ne comprends pas très bien, je peux tester avec un header qui n'est pas en absolu peut-être ? C'est peut-être aussi mon loader que j'ai mis dans le header ? 

Et tu as une idée de pourquoi ca fonctionne sur Chrome et pas sur les deux autres navigateurs (Firefox et safari) ?

**Comment by Pepite-World** [comment]
Bon ben c'est mon loader qui fait chier...

**Comment by Pepite-World** [comment]
Voila je l'ai mis dans le footer héhé !

**Comment by 5AMsan** [comment]
Tu pourras laisser un message à ces grosse tanches du support... Bravo en tout cas.

**Comment by Pepite-World** [comment]
haha ouais j'y manquerai pas ! Merci d'avoir regardé.
