### ISSUE TITLE
Video 

### ISSUE THREAD

**Issue by Pepite-World** [Pepite-World/slideur-pepite#2]
J'ai testé avec deux liens vimeo et youtube mais la vidéo ne s'affiche pas. 

![Capture d’écran 2024-09-04 à 16 27 16](https://github.com/user-attachments/assets/56844aec-d3cd-44e1-a386-2eea79c34d30)
![Capture d’écran 2024-09-04 à 16 29 23](https://github.com/user-attachments/assets/8da62757-31b0-4bdb-9dc0-2183634aefa2)
![Capture d’écran 2024-09-04 à 16 29 34](https://github.com/user-attachments/assets/2944c910-1c14-4221-8124-860adef1631e)

**Comment by 5AMsan** [comment]
![image](https://github.com/user-attachments/assets/d45eeb70-2eda-4fb1-bd50-f7bbef38a45c)
OK en dev, tu dois pas être à jour quelque part.

**Comment by Pepite-World** [comment]
D'acc, pour digger tu pourrais me dire : 

- quelle version de php tu as ?
- tu as mis des valeurs dans les champs dimensions ?
- tu as quelle version de divi ? 
- tu as mis quel lien vimeo ? 

Peut-être qu'il faudrait que je bosse direct sur un sous domaine et non en local c'est peut-être ca le soucis...

**Comment by 5AMsan** [comment]
J'ai mis à jour le plugin, je pense qu'il y a eu un souci avec le build

**Comment by 5AMsan** [comment]
Pour les dimensions on a un autre ticket. je ferme celui-ci, toutes les vidéos que j'ai testées sont OK
