### ISSUE TITLE
Case à cocher par slide header noir/blanc

### ISSUE THREAD

**Issue by Pepite-World** [Pepite-World/slideur-pepite#5]

**Comment by 5AMsan** [comment]
Présente dans la section Design > Text > Text color

**Comment by Pepite-World** [comment]
Oui cette partie permet de gérer la couleur du titre de la slide. Peux-tu ajouter une case à cocher pour que le header et le compteur passent en noir ? 

De base ils sont en blanc et une case à cocher pour les passer en noir. 

J'ai fait deux classes : 

.swiper-item-count
.swiper-item-count-black

.header-pepite
.header-pepite-black

**Comment by 5AMsan** [comment]
> J'ai fait deux classes :
> .swiper-item-count .swiper-item-count-black
> .header-pepite .header-pepite-black

En fait il faut étendre tes deux classes avec `.et_pb_bg_layout_light` et `.et_pb_bg_layout_dark` pour définir la couleur que tu souhaites, directement dans tes styles, je passe la classe sur la balise Body (

```
.swiper-item-count,
.header-pepite{
  color: black;
}
body.et_pb_bg_layout_dark .swiper-item-count,  
body.et_pb_bg_layout_dark .header-pepite {
  color: white;
}
```

**Comment by Pepite-World** [comment]
Je l'ai rajouté dans la feuille css du thème enfant : 

body.et_pb_bg_layout_dark .swiper-item-count,  
body.et_pb_bg_layout_dark .header-pepite, body.et_pb_bg_layout_dark .header-pepite h1, 
body.et_pb_bg_layout_dark .header-pepite a{
  color: white;
}

**Comment by Pepite-World** [comment]
Oki merci ! J'ai ajouté ce code css dans le théme enfant : 


body.et_pb_bg_layout_dark .swiper-item-count,  
body.et_pb_bg_layout_dark .header-pepite, body.et_pb_bg_layout_dark .header-pepite h1, 
body.et_pb_bg_layout_dark .header-pepite a{
  color: white;
}

body.et_pb_bg_layout_light .swiper-item-count,  
body.et_pb_bg_layout_light .header-pepite, body.et_pb_bg_layout_light .header-pepite h1, 
body.et_pb_bg_layout_light .header-pepite a{
  color: black;
}

**Comment by 5AMsan** [comment]
> Oki merci ! J'ai ajouté ce code css dans le théme enfant :
> body.et_pb_bg_layout_light .swiper-item-count, body.et_pb_bg_layout_light .header-pepite, body.et_pb_bg_layout_light .header-pepite h1, body.et_pb_bg_layout_light .header-pepite a{ color: black; }

y'a pas de classe "et_pb_bg_layout_light" sur le body, donc c'est juste :
```
.swiper-item-count,
.header-pepite, 
.header-pepite h1,
.header-pepite a {
  color: black;
}
```

**Comment by Pepite-World** [comment]
Oki, j'ai maj le css

**Comment by 5AMsan** [comment]
T'as oublié le `:after`
![image](https://github.com/user-attachments/assets/8f8f1580-1c65-45cf-b031-6e3a63f77555)

**Comment by 5AMsan** [comment]
Celui là aussi faut l'ajouter du coup
![image](https://github.com/user-attachments/assets/daa417ed-5759-431f-819c-706552948f26)

**Comment by Pepite-World** [comment]
C'est bon pour le :after à coté de fonderie. Par contre il y a un soucis de couleur aléatoire : quand tu changes les slides, les classes avec "body.et_pb_bg_layout_dark " ne sont parfois pas prisent en compte et reste en noir... tu peux tester en changeant plusieurs fois de slide. Typiquement quand tu charges la premiere slide, les éléments sont en noir alors que je souhaite qu'ils soit en blanc. Tu changes de slide pour la slide 2 et quand tu reviens sur la 1, les éléments sont en blanc.

**Comment by 5AMsan** [comment]
EN fait ça semble aussi lié à la boucle de lecture, en la virant j'ai pas l'impression qu'il y ait le problème

**Comment by Pepite-World** [comment]
Effectivement mais on souhaiterait que le carrousel boucle. Si il n'est pas en boucle, la navigation entre les projets est relou. Par exemple, je suis dans la page d'accueil et je suis au projet 12. Si je veux revenir sur le projet 3 il faut skipper 11 projets...

**Comment by 5AMsan** [comment]
J'ai fait des modif, tu me diras comment c'est à la vitesse d'une visite normale d'abord et en mode brute ensuite...

**Comment by Pepite-World** [comment]
Quand on arrive sur la première la concordance est good. De 1 à 5 c'est bon. Par contre dés qu'on passe de la 5 à la 1 avec une boucle la concordance est décalée.

**Comment by 5AMsan** [comment]
ok, je vois le genre... Merci pour l'info

Le mer. 18 sept. 2024 à 09:49, Pepite-World ***@***.***> a
écrit :

**Comment by 5AMsan** [comment]
Ok sur mon espace de test, sur le tiens aussi je crois bien

**Comment by Pepite-World** [comment]
Il est possible de réduire le délais de transition de changement de couleur pour qu'il soit instantané ?

**Comment by 5AMsan** [comment]
instantané non, sinon il foire comme tu le sais déjà. J'ai un décalage de 50ms (contre 500 auparavant) et plus bas ça fonctionnera plus.
