### ISSUE TITLE
Zone de click url 

### ISSUE THREAD

**Issue by Pepite-World** [Pepite-World/slideur-pepite#7]
La zone de click pour accéder à ce qui est mis dans le champs l'url prend toute la zone de la side. Il faudrait que la zone soit que sur le titre.

**Comment by Pepite-World** [comment]
Il faudrait redéfinir la zone de click, elle n'est pas sur le titre. Peut-être que mon positionnement du titre en absolute n'arrange pas.

**Comment by 5AMsan** [comment]
OK chez toi et chez moi

**Comment by Pepite-World** [comment]
J'ai quelques soucis de mon coté pour la zone de click et le curseur : 


https://github.com/user-attachments/assets/c5d8306c-1572-4976-aa10-c45ff861f797

**Comment by 5AMsan** [comment]
Elle est bien trop petite ta zone, t'arrive pas à la chopper

**Comment by 5AMsan** [comment]
Je mets toujours un padding sur les <a> pour ça

**Comment by Pepite-World** [comment]
Ta phrase n'est pas complète ^^ mais j'ai pu régler le soucis en changeant la façon de placer le titre : 

.pesl_slide_description {
    z-index: 10;
    position: absolute;
    top: auto!important;
	bottom:0;
	display:flex;
	justify-content:flex-start!important;
	align-items:center;
	padding:2rem;
    left: 0!important;
    width: 100%!important;
    height: auto!important;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;

}
