### ISSUE TITLE
Placement du titre des slides

### ISSUE THREAD

**Issue by 5AMsan** [Pepite-World/slideur-pepite#9]
Comment on place le titre pour chaque slide en fait ?

**Comment by Pepite-World** [comment]
Je les place en bas de slide à gauche, le compteur à droite. Je les ai placé avec la position absolute (à voir dans la feuille css de mon thème enfant).  

![Capture d’écran 2024-09-10 à 10 45 00](https://github.com/user-attachments/assets/5c401dc4-66b1-4e83-b2bf-ad60dcf32caf)

**Comment by 5AMsan** [comment]
Ok je te laisse gérer.
